name: ubuntu

on:
  push:
    branches:
      - master
      - "*-stable"
      - "*/ci-check"
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 3.1, "3.0", 2.7, ruby-head ]
        opal: [ 1.0.3, 1.3, 1.5.1, master ]

    runs-on: ${{ matrix.os }}

    env:
      OPAL_VERSION: ${{ matrix.opal }}

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup project
        run: bin/setup
      - name: Run opal-rspec test
        run: "bundle exec exe/opal-rspec spec-opal-passing"
      - name: Run rspec test
        run: bundle exec rspec
